### ISSUE TITLE
No module named config in Planet builder

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/scripts#53]
Since the server upgrade to Debian Bookworm, the following error occurs when trying to run `scripts/website/pma-planet`

```
Traceback (most recent call last):
  File "/home/builder/venus/planet.py", line 60, in <module>
    from planet import config
  File "/home/builder/venus/planet/__init__.py", line 8, in <module>
    import config
ModuleNotFoundError: No module named 'config'
```

**Comment by williamdes** [comment]
Could be related to phpmyadmin/website#160

**Comment by williamdes** [comment]
I changed it to `@hourly /usr/bin/python3 /home/builder/website/manage.py fetch_planet`
Let's see

**Comment by williamdes** [comment]
I stopped the crons for planet, after a lot of patching in the venus code, it's still not python3 compatible.
My test command was `PYTHONPATH=/home/builder/venus/planet python /home/builder/venus/planet.py ~/planet/planet.ini` as builder

**Comment by williamdes** [comment]
@ibennetch There is currently a vote on the topic of Planet in Element. Could you have a look please ?

**Comment by williamdes** [comment]
Planet is gone.
